-- Replace Master Data Script
-- Generated at 2026-01-27T12:01:48.556Z

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Delete dependencies first
DELETE FROM vgvina_sales_order_items;
DELETE FROM vgvina_purchase_order_items;
DELETE FROM vgvina_sales_orders;
DELETE FROM vgvina_purchase_orders;
DELETE FROM vgvina_financial_transactions;
DELETE FROM vgvina_debt_transactions;
DELETE FROM vgvina_partners;
DELETE FROM vgvina_products;
DELETE FROM vgvina_product_categories;

-- Helper for product categories
CREATE OR REPLACE FUNCTION get_or_create_product_category(p_name TEXT) RETURNS UUID AS $$
DECLARE
    v_id UUID;
BEGIN
    IF p_name IS NULL OR p_name = '' THEN 
        SELECT id INTO v_id FROM vgvina_product_categories WHERE name = 'General' LIMIT 1;
        IF v_id IS NULL THEN
            INSERT INTO vgvina_product_categories (name) VALUES ('General') RETURNING id INTO v_id;
        END IF;
        RETURN v_id;
    END IF;
    SELECT id INTO v_id FROM vgvina_product_categories WHERE name = p_name LIMIT 1;
    IF v_id IS NULL THEN
        INSERT INTO vgvina_product_categories (name) VALUES (p_name) RETURNING id INTO v_id;
    END IF;
    RETURN v_id;
END;
$$ LANGUAGE plpgsql;

-- INSERT CUSTOMERS/PARTNERS

INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('Bắp Ngô', 'CUSTOMER', NULL, NULL, '391 hùng vương', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('CT Nhật Kim Thành', 'CUSTOMER', 707666073, NULL, 'Số 6 Đường 84 Cao Lỗ P4 Q8 ( kế nhà hàng thuận phát)', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('Nguyễn Tùng', 'CUSTOMER', 967222352, NULL, NULL, NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('Yên Sushi', 'CUSTOMER', 935221299, NULL, '11 Hồ Sĩ Dương, Cẩm Lệ , Đà Nẵng', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('Anh Quân', 'CUSTOMER', NULL, NULL, NULL, NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('Ms Nhi (CTY HAKUSHOKU)', 'CUSTOMER', 961452067, NULL, '142 Đô Đốc Bảo, phường Trần Phú, Quy Nhơn', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('CÔNG TY GOLDEN VIỆT NHẬT', 'CUSTOMER', 318809875, NULL, '81 NGUYỄN TRÃI.', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('NÀNG MIND- ĐỒNG NAI', 'CUSTOMER', 933927666, NULL, 'CAO TỐC -LONG THÀNH', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('CT TNHH XNK TM PHÚC HÙNG', 'CUSTOMER', 318509751, 'tranduc1203@gmail.com', '65 PHAN CHU TRINH PHƯỜNG BÌNH THẠNH TPHCM', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('CT CP DV TM HADU', 'CUSTOMER', 978821400, NULL, '77 Trung Hòa', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('MR HẢI - Nguyễn Tuân', 'CUSTOMER', 964023333, NULL, 'phòng 3401 Tòa Ps Gold Season 47 Nguyễn Tuân Thanh Xuân Trung', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('Ms Giang Thúy Linh - HN', 'CUSTOMER', 947566360, NULL, 'Đối diện số nhà 101 ngõ 49 phố Thúy Lĩnh, Lĩnh Nam', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('Hiền Eco', 'CUSTOMER', NULL, NULL, NULL, NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('MR TUÂN HN', 'CUSTOMER', NULL, NULL, '8a - Yên Phụ - Tây hồ', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('MR NGỌC HN (CT SANMARU)', 'CUSTOMER', 336026096, NULL, '59 Triệu Việt Vương/ 860 Bạch Đằng', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('CHI HƯƠNG Q1', 'CUSTOMER', 364001943, NULL, '5/41 ĐƯỜNG NGUYỄN TRUNG NGẠN  PHƯỜNG BẾN NGHÉ', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('KHÁCH LẺ', 'CUSTOMER', NULL, NULL, NULL, NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('CÔNG TY', 'CUSTOMER', 2583511179, NULL, NULL, NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('GOFOOD-SG (CT TNHH FBC SÀI GÒN)', 'CUSTOMER', '0978 707 783', NULL, '111 Đường B Trưng Trắc, Hiệp Bình Chánh, Thủ Đức, HCM', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('Anh Đức Quảng Bình', 'CUSTOMER', NULL, NULL, NULL, NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('Nhà hàng biển rừng', 'CUSTOMER', 917551165, NULL, 'Thạch hà hà tĩnh. . nhà hàng nằm trên quốc lộ 1A.', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('HÂY SUSHI CẦN THƠ', 'CUSTOMER', NULL, NULL, '84/7Bis Mậu Thân', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('TAKO IKA', 'CUSTOMER', '''00567800866', NULL, 'C14 hoàng quốc việt. Phú thuận. Quận 7', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('CT TNHH MEAT FARM', 'CUSTOMER', '096 9413202', NULL, 'Vila D32 -33, KĐT The Maner, đường Hoàng Trọng Mậu, p. Mỹ Đình', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('Chị Vân Mễ Trì', 'CUSTOMER', NULL, NULL, NULL, NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('MS ĐÌNH PHONG - CS3 DÃ TƯỢNG', 'CUSTOMER', 396800323, NULL, 'Số 7 Dã TƯỢNG', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('MR - QUỐC HOÀN', 'CUSTOMER', 848559999, NULL, 'Sảnh 1, ct 02, cc viện 103, tân triều , thanh trì, hn', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('Chị Oanh Đồng Nai (Quán chân gà sốt thái)', 'CUSTOMER', '097 3439048', NULL, NULL, NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('ANH VIỆT - SIÊU THỊ', 'CUSTOMER', '0364319824, 0366886361', NULL, '90 Đường H, Khu dân cư Bình Điền', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('ANH ĐÔ', 'CUSTOMER', 939900335, NULL, '861/27/40 TRẦN XUÂN SOẠN', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('MS HỒNG- CHỢ MỚI LONG THÀNH ĐỒNG NAI', 'CUSTOMER', 982083040, NULL, 'CHỢ MỚI LONG THÀNH ĐỒNG NAI', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('anh Duy', 'CUSTOMER', '0943318 338', NULL, 'số 7 đồng xuân/191 Bà Triệu', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('Anh Nguyễn Anh - Sashimi Linh Đàm (HKD Dương sushi)', 'CUSTOMER', 971457868, NULL, 'Đối diện số 93 phố Bằng Liệt, Hà Nội', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('Ken ss Đà Nẵng', 'CUSTOMER', 905338441, NULL, '52 Hoàng Văn Thụ, Đà Nẵng', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('MR ĐÌNH PHONG - CS1 BÁT ĐÀN', 'CUSTOMER', 985217812, NULL, '47 Bát Đàn Hoàn Kiếm HN', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('Mr Phong sushi', 'CUSTOMER', 866836274, NULL, NULL, NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('Mr Vỹ- Đà Nẵng', 'CUSTOMER', 329294466, NULL, '235 Phan Đăng Lưu, Đà Nẵng', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('Minori vinhome long biên (Cty Lê Gia)', 'CUSTOMER', NULL, NULL, NULL, NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('CT LÊ GiA (MINORI CS2)', 'CUSTOMER', 988443523, NULL, 'SB23-135, Dự án khu đô thị Gia Lâm - Vinhome ocean Park . Xã Đa Tốn', 110047995);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('Ms Hương mễ trì (C HƯƠNG VOV)', 'CUSTOMER', 988299292, NULL, 'Số 4 TT 5 Khu VOV, Mễ Trì, Nam Từ Liêm, HN', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('ANH PHI', 'CUSTOMER', 967823909, NULL, '123/15a Huỳnh Thiện Lộc', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('Anh Thừa - Sushi Sashimi', 'CUSTOMER', 786965656, NULL, NULL, NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('Quán Tanaka Tei', 'CUSTOMER', 981480645, NULL, '2 Bàu Bàng, P.13, Q.Tân Bình, TpHCM', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('Family sushi', 'CUSTOMER', 971482727, NULL, NULL, NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('Thơm - NT', 'CUSTOMER', '090 538 5123', NULL, 'Nha Trang', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('Nhà hàng The Dining (CT TRIBE DAISEI)', 'CUSTOMER', 354782260, NULL, 'Toà nhà roygent park, số 3 đường số 1 Kđt ven sông Lạch Tray Lê chân Hải Phòng', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('CT TNHH TM DV VÀ TP PHƯƠNG LINH', 'CUSTOMER', 968303930, NULL, '140 bạch mai', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('MR TÂN- HẢI PHÒNG', 'CUSTOMER', 936299333, NULL, '46 Mương Cứu Hỏa , phường Kênh Dương, Quận Lê Chân tp Hải Phòng', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('CT TNHH SƠN BA (MR THÀNH VIN)', 'CUSTOMER', 912967668, NULL, '12 Lý Đạo Thành, Phường Tràng Tiền, Quận Hoàn Kiếm, Hà Nội', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('NH YAKI YUM - NGUYỄN VĂN LỘC', 'CUSTOMER', 567788778, NULL, '131 Nguyễn Văn Lộc, P. Mộ Lao, Hà Đông , HN', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('MR THÊU - HN -CS2', 'CUSTOMER', '0978 948 729 Cs2', NULL, 'Số 9 ngõ 207/167 Xuân Đỉnh', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('CT TNHH GOLDEN FINE FOODS', 'CUSTOMER', '0902056871 - Mỹ Anh', NULL, '38 ngách 27 ngõ 41 phố Vọng, Hai Bà Trưng, HN', 110726059);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('MR Nhật Trần (HKD PEZZI)', 'CUSTOMER', 399432487, NULL, 'Số 10 ngõ 9 Liễu Giai', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('Anh Minh Lâm', 'CUSTOMER', 917891637, NULL, NULL, NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('Thầy Bách', 'CUSTOMER', 989975825, NULL, NULL, NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('Ashita SS - Buôn Ma Thuột', 'CUSTOMER', 854242988, NULL, '227/2 hà huy tập phường Tân Lợi TP Buôn Ma Thuột', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('ANH HẢI TRIỀU', 'CUSTOMER', 903193073, NULL, '270/9 HÒA HẢO', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('CT TNHH MTV TM NAM ANH FOODS (MR VINH- ĐÀ NẴNG)', 'CUSTOMER', '''0985400043', NULL, 'Gửi bến xe Đà Nẵng', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('ANH HOÀNG VŨ', 'CUSTOMER', 792262320, NULL, '17/11/1 ĐƯỜNG SỐ 14', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('Anh Triệt- Tây Ninh', 'CUSTOMER', '038 339 2429', NULL, 'bến xe Hoà Thành, Tây Ninh', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('Sushi Chef Tran Dan', 'CUSTOMER', 339234555, NULL, '253 trần hưng đạo ninh bình', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('MR HIẾU- VŨNG TÀU', 'CUSTOMER', 978698980, NULL, '242 Cách Mạng tháng 8 - Bà Rịa Vũng Tàu', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('CÔNG TY TM& DV THỰC PHẨM SỐ 1', 'CUSTOMER', 932312189, NULL, 'SỐ 1 ĐƯỜNG SỐ 1,KP4', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('Thiệu', 'CUSTOMER', NULL, NULL, NULL, NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('Le Thanh Jfood (CT HS BÌNH MINH SG)', 'CUSTOMER', 357924235, NULL, 'bến xe miền đông cũ', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('Hàng thanh lý', 'CUSTOMER', NULL, NULL, NULL, NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('MR HẢI - HN', 'CUSTOMER', 388498483, NULL, '9 ngõ 113 Hoàng Cầu', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('Big Sushi - Lê Nhã', 'CUSTOMER', 866160224, NULL, 'Đà Nẵng', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('CT KYOTO YAKINIKU', 'CUSTOMER', 934896596, NULL, '04 Chi Lăng, Phường Hải Châu, Thành phố Đà Nẵng, Việt Nam', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('HÀ DƯƠNG FOODS- SG', 'CUSTOMER', 902375853, NULL, 'Nhà xe Phương Nam quận 5, TPHCM', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('CHỊ MỸ LINH- Thủ Đức', 'CUSTOMER', 975170614, NULL, '709 TÔ NGỌC VÂN', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('NH NAGI SUSHI (BT)', 'CUSTOMER', 906389647, NULL, '104 D5', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('NH NAGI 2 (Nagi Gò Vấp)', 'CUSTOMER', NULL, NULL, '672a 24 phan văn trị', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('ANH ĐỨC Q7 (Street Sushi)', 'CUSTOMER', 909744369, NULL, NULL, NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('CT TNHH XK & NK AN PHÚ (HSX 55 MỄ TRÌ)', 'CUSTOMER', NULL, NULL, NULL, NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('MS TRINH- QUẬN 7', 'CUSTOMER', '036 7810160/ 0329774225', NULL, '1172/11a Huỳnh Tấn Phát , P.Tân Phú, Q.7, HCM', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('CT TNHH NEW FRESH FOODS', 'CUSTOMER', 909689009, NULL, 'CH2 38/31/06 CHẾ LAN VIÊN , P.TÂY THẠNH , QUẬN TÂN PHÚ', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('MARUSEI-SG', 'CUSTOMER', 969254250, NULL, '18A Lưu Trọng Lư', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('CT TNHH ĐT TS PHÚ THỊNH', 'CUSTOMER', 919997208, NULL, 'C16 Huỳnh tấn phát', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('MR LEE MINH HEO - HN', 'CUSTOMER', 359308379, NULL, NULL, NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('MS THỦY TIÊN', 'CUSTOMER', 982575888, NULL, '133 Hoàng Như Tiếp Long Biên HN', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('MS THANH THẢO- SG', 'CUSTOMER', 347102055, NULL, '224/6/36 ung văn khiêm', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('MR HIỆP- BẮC GIANG', 'CUSTOMER', 985829310, NULL, '158 hùng vương, phường Hoàng Văn Thụ, tp Bắc Giang', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('MR LƯỢNG - BẮC NINH', 'CUSTOMER', 909946299, NULL, 'Số nhà 68 đường Trần Quốc Toản phường Ninh Xá thành phố Bắc Ninh', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('Thảo- PY', 'CUSTOMER', 964345637, NULL, NULL, NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('CHỊ LAN VY', 'CUSTOMER', 389207742, NULL, '387 TRẦN NHÂN TÔNG', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('Duyên Eco', 'CUSTOMER', NULL, NULL, NULL, NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('Chị Bình xưởng', 'CUSTOMER', NULL, NULL, NULL, NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('Vương Xưởng', 'CUSTOMER', NULL, NULL, NULL, NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('Tuấn Xưởng', 'CUSTOMER', NULL, NULL, NULL, NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('Sa Eco', 'CUSTOMER', 345652929, NULL, NULL, NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('Trung-Eco', 'CUSTOMER', NULL, NULL, NULL, NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('Lý tk xưởng', 'CUSTOMER', NULL, NULL, NULL, NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('Nhà hàng Mitami Japanese', 'CUSTOMER', NULL, NULL, '72 Nguyễn Thị Minh Khai', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('ANH TRUNG GIA LAI', 'CUSTOMER', 824877777, NULL, 'BẾN XE CŨ AN KHÊ', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('Anh Quang Thất- HN', 'CUSTOMER', '098 458 57 27', NULL, '5 Kim Mã Thượng', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('Huyền Trang - Nha Trang', 'CUSTOMER', 942008100, NULL, '26 lê thanh nghị, vĩnh nguyên, dã tượng rẽ vào', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('A Sơn Eco', 'CUSTOMER', 'co', NULL, NULL, NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('Trang Vương Eco', 'CUSTOMER', NULL, NULL, NULL, NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('MARUSEI-HN', 'CUSTOMER', 869924473, NULL, 'Xóm Xa, Sơn Đồng, Hoài Đức, Hà Nội', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('Mr HOÀN ECO', 'CUSTOMER', NULL, NULL, NULL, NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('CT TNHH KAKINOKI (MS PHƯƠNG -SG)', 'CUSTOMER', NULL, NULL, '12 E PHAM VIẾT CHÁNH', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('Chị Lan- Nha Trang', 'CUSTOMER', 905267077, NULL, '94 Lê Hồng Phong', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('MR THUẬN- SG (NOWZOON)', 'CUSTOMER', NULL, NULL, NULL, NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('SS GARDEN Chính Kinh', 'CUSTOMER', 96595256, NULL, '313 Chính Kinh', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('C Hồng Ánh HN (CTY MOO JIN)', 'CUSTOMER', 965185785, NULL, 'khách sạn Grace - Mặt sau chung cư CT6 - Kđt Mỹ Đình Sông Đà, HN', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('MS MINH TRANG- 81/2 HOÀNG DIỆU, NHA TRANG', 'CUSTOMER', 896690605, NULL, NULL, NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('CT TNHH TISM & CO ( MR NAM- Nguyễn Văn Ngọc)', 'CUSTOMER', NULL, NULL, '30 Nguyễn Văn Ngọc Cs2', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('CT TNHH TM DV HAN YANG', 'CUSTOMER', '0902 145 586', NULL, '14 Phan Lại, KĐT Regal Legent, Bảo Ninh, Đồng Hới, Quảng Bình', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('Tiến Quảng Trị', 'CUSTOMER', NULL, NULL, NULL, NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('CT TNHH ĐT NGỌC THỊNH PHÁT (MR TÌNH)', 'CUSTOMER', '0983781285 / ''033 433 1419', NULL, '49 triệu việt vương/ 25 Tôn Đản', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('MR GIANG- VẠN GIÃ', 'CUSTOMER', 985759116, NULL, 'Vạn Ninh, Vạn Giã', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('HANA SS- THÁI BÌNH', 'CUSTOMER', 966066897, NULL, '17 hai ba trưng lê hồng phong tp Thái Bình', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('SS GARDEN- NGUYỄN VĂN LỘC', 'CUSTOMER', '096 5952586/034 5219499', NULL, NULL, NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('NH QUẢNG NINH-CS3', 'CUSTOMER', 377096113, NULL, 'Ô 7,8 SH18, Phú Gia 2, Vinhome Cẩm Bình, Cẩm Phả, Quảng Ninh', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('CT 138 ENT (LẨU CÁ THANH ĐA) - SG', 'CUSTOMER', 2838981536, NULL, '860/75/1 xố viết nghệ tĩnh', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('ANH DUNG QUAN 2', 'CUSTOMER', NULL, NULL, '98 TRẦN NÃO', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('AKIKO SUSHI', 'CUSTOMER', 362783028, NULL, '398 PHAN XÍCH LONG', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('CHỊ HỒNG- BINH DƯƠNG', 'CUSTOMER', 32831922, NULL, 'SỐ 4 MỸ PHƯỚC', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('CT TNHH MTV ĐẠI VY (NH MAYONAKA)', 'CUSTOMER', 909960942, NULL, '175 ĐỀ THÁM', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('MR HÙNG- MAI HẮC ĐẾ, HN', 'CUSTOMER', 523209999, NULL, '98 mai hắc đế phường', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('MR QUÝ - ĐỒNG NAI', 'CUSTOMER', NULL, NULL, NULL, NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('SS IKUSACHI- SG', 'CUSTOMER', NULL, NULL, '174/36 nguyễn thiện thuật', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('Mr Phong - ĐN', 'CUSTOMER', 339358577, NULL, NULL, NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('CT Anh Vũ (Chị Hương)', 'CUSTOMER', 919861964, NULL, 'Số 9 Nguyễn Quang Bích', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('Anh Trung- cơ động', 'CUSTOMER', 1111000000, NULL, NULL, NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('MS TUYỀN- THỦ ĐỨC', 'CUSTOMER', 918380512, NULL, '20 NGUYỄN ĐANG GIAI', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('MS DƯƠNG MINH LÝ- QUẢNG NINH', 'CUSTOMER', 987499919, NULL, 'A3-02 Monbay Hạ Long, Quảng Ninh', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('MR TOÀN - ĐÀ NẴNG', 'CUSTOMER', 944874874, NULL, '35 Lê Hồng Phong', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('CHỊ CHÂU TO', 'CUSTOMER', 908268450, NULL, '38 ĐIỆN BIÊN PHỦ', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('NH UNI SUSHI', 'CUSTOMER', NULL, NULL, NULL, NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('ANH LỘC - ĐÔNG NAI (HKD NGUYỄN VĂN QUÝ)', 'CUSTOMER', 399785663, NULL, 'ĐÔNG NAI', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('CT TNHH TM TP THANH HOA', 'CUSTOMER', 987491638, NULL, 'số nhà 18ax16 bộ công an phường khương Trung đi ngõ 93 Hoàng văn Thái vào', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('MR NHÂN SS- 290 KIM MÃ, HN', 'CUSTOMER', NULL, NULL, NULL, NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('ANH ĐÔNG (PHÚ QUỐC)', 'CUSTOMER', '0763882043-', NULL, '98b Trần hưng đạo ,khu phố 7', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('MR THỦY- NGHỆ AN (FUJIMO)', 'CUSTOMER', 974243331, NULL, 'nhà hàng fujimo số 6 Trừơng Thịnh Phát, Lê Nin , TP Vinh (Cạnh Lotte Vinh)', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('Anh Long Hà Nội', 'CUSTOMER', '096 670 3188', NULL, 'Cầu Giấy-Hà Nội', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('Kin Sushi (HKD)', 'CUSTOMER', '08.38.39.22.55', NULL, '01 Hùng Vương- Thị Trấn Liên Nghĩa- Đức Trọng- Lâm Đồng', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('ANH HỮU THUẬN', 'CUSTOMER', 794261773, NULL, 'RẠCH GIÁ KIÊM GIANG', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('HKD Y SA BI (MS GIA HÂN- TRÀ VINH)', 'CUSTOMER', 901021197, NULL, NULL, NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('NH QUẢNG NINH-CS1', 'CUSTOMER', 397879043, NULL, '176 Huỳnh Thúc Kháng, Hồng Hà, Hạ Long, Quảng Ninh', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('NPP Trung Hà Tĩnh', 'CUSTOMER', 919307889, NULL, 'Tp Hà Tính', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('SUSHI MINH', 'CUSTOMER', 909188211, NULL, '13 Hậu Giang', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('NH RI SUSHI (MR PHÚC SUSHI)', 'CUSTOMER', 903169192, NULL, '53 đường 3/2, P.11, Q.10, HCM (Qua ngã tư Cao Thắng, đối diện chung cư Hà Đô)', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('MR THIỆU - NHA TRANG (CÁ NHÂN)', 'CUSTOMER', NULL, NULL, NULL, NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('MS LÌ - SÀI GÒN', 'CUSTOMER', 397593050, NULL, '76/14 đường 100 phuong tân phú q9, HCM', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('CT TNHH SX-TM THIÊN ÂN PHÁT (MR ĐỖ XUÂN-NT)', 'CUSTOMER', 935051700, NULL, 'Tổ 8, Vĩnh Điềm Thượng, Phường Tây Nha Trang, Tỉnh Khánh Hòa, Việt Nam', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('CN DNTN XD LONG PHƯỚC (MR CHÁNH-VT)', 'CUSTOMER', 938900900, NULL, '9 Hạ Long, Phường 2. Tp Vũng Tàu', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('MR LEE - PHÚ QUỐC', 'CUSTOMER', 766311966, NULL, NULL, NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('MR ĐỊNH- NHA TRANG (HKD EKI)', 'CUSTOMER', NULL, NULL, NULL, NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('MR DUY - VĂN CAO, HN', 'CUSTOMER', 334339699, NULL, '47A Văn Cao', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('NH BABABA- CN ĐÀ NẴNG', 'CUSTOMER', '077.444.6485.', NULL, '333 Hồ Nghinh, P. Phước Mỹ, Q. Sơn Trà, TP. Đà Nẵng - Phương', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('MR THỊNH- ĐÀ NẴNG', 'CUSTOMER', '0978 430 584', NULL, NULL, NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('Marusei ĐN', 'CUSTOMER', 936134134, NULL, '96 Dương Văn An, Mân Thái, Sơn Trà, Đà Nẵng', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('NH HS HÀM NINH GRANDWORLD PHÚ QUỐC', 'CUSTOMER', '083 358 0337', NULL, 'Phú Quốc', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('CT GREENGOOD', 'CUSTOMER', '''00388255246', NULL, '193 Bình Thới, P9, Q11, Hcm', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('CT TNHH XNK SK FOODS VN', 'CUSTOMER', '0905711122 - Ly', NULL, '29/1 Nguyễn Đức Trung, Thanh Khê, Đà Nẵng', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('NH QUẢNG NINH- CS2 (CTY JT)', 'CUSTOMER', 843302155, NULL, 'Hùng thắng Hạ Long', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('CT TNHH TM DV VINROLL VN ( MR PHÚC- THỦ ĐỨC))', 'CUSTOMER', 362454918, NULL, 'TÒA S803 VINHOMES GRAND PARK', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('CN CT CP TM VÀ DV VIET DELI - NHA TRANG', 'CUSTOMER', 385121725, NULL, 'Tầng 2 - Khách sạn Citadines, Số 62 Trần Phú', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('CT TNHH TM DV ONE MOREANH (MR TUẤN NGHĨA- ĐÀ NẴNG)', 'CUSTOMER', 379098205, NULL, '26 Quang Trung ,Thạch Thang, Hải Châu, Đà nẵng', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('MS MAI TRINH- ĐÀ NẴNG', 'CUSTOMER', 377990600, NULL, NULL, NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('ANH HỢP - ĐÀ NẴNG (HKD FUNE SS)', 'CUSTOMER', NULL, NULL, 947889468, NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('GOFOOD- HN', 'CUSTOMER', 966864947, NULL, 'Đội 1 (cạnh giếng miếu) , thôn Sơn Đồng , Tiên Phương, chương Mỹ Hà Nội', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('CT TNHH SUSHITO RESTAURANT (NHÀ KHO)- SG', 'CUSTOMER', '0865 299 965', NULL, '79C Song Hành', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('CT CP TẬP ĐOÀN DU THUYỀN- NHA TRANG', 'CUSTOMER', 868488068, NULL, 'Ana Marina, Phạm Văn Đồng, Nha Trang', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('MR MẠNH TOCHANSISHI', 'CUSTOMER', NULL, NULL, NULL, NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('NH BABABA-PHÚ QUỐC', 'CUSTOMER', '096 256 1356- Anh Tâm', NULL, 'Phú Quốc', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('CT TNHH TISM & CO ( MR NAM- LA THÀNH,HN)', 'CUSTOMER', 338280991, NULL, '1144 Đê La Thành', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('Thực Phẩm Ngày Mới', 'CUSTOMER', 931312463, 'thucphamngaymoi2021@gmail.com', '212 Nguyễn Văn Kỉnh', 316960694);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('CT CP DV LƯƠNG NGUYÊN', 'CUSTOMER', '0769 492 882/ 0902 943 898', NULL, 'K3-1, tầng một, kho K2-K3, đường N2 và N4, Khu Thương mại Bắc thuộc Khu Chế Xuất Tân Thuận
, Phường Tân Thuận Đông, Quận 7, Thành phố Hồ Chí Minh', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('BÌNH- HN', 'CUSTOMER', 936225889, NULL, NULL, NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('MS GIANG- CẦN THƠ', 'CUSTOMER', 939607604, NULL, NULL, NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('MR THIÊN SS- N.TRANG (HKD SAKURA BBQ)', 'CUSTOMER', '096 112 35 88', NULL, 'số 7 Phù Đổng', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('CT TNHH UMEYAKIA (MR NHÂN- THE VIEW ĐÀ NẴNG)', 'CUSTOMER', '0906 724 195', NULL, 'tầng 1 du thuyền marina - đối diện 461 trần hưng đạo - an hải tây -sơn trà- đà nẵng.', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('CT CP QL KS VÀ KND LYNN TIMES (MR ĐINH ĐỒNG)', 'CUSTOMER', NULL, NULL, NULL, NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('SS O BA- SG', 'CUSTOMER', '097 682 6875', NULL, 'SỐ 1 NGUYỄN CÔNG TRỨ', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('Chị Hương VOV (cty DELMAR)', 'CUSTOMER', '00988 299 292', NULL, 'Số 4 TT 5 Khu VOV, Mễ Trì, Nam Từ Liêm, HN', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('MR ÁNH ECO-HN', 'CUSTOMER', 932388544, NULL, NULL, NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('CT TNHH SƠN MAI VỊ BIỂN (MR NGỌC-NHA TRANG)', 'CUSTOMER', '098 477 55 77', NULL, NULL, NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('CT TNHH SAKURA SUSHI', 'CUSTOMER', 1234444444, NULL, '30 Lý Tự Trọng', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('CT TNHH ĐẢO HẢI SẢN', 'CUSTOMER', 19001980, NULL, '34/35 Trần Thái Tông', 313566925);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('CT TNHH TM TP SH (SH FOODS)', 'CUSTOMER', 902428384, NULL, '102/3 Quang Trung, khu phố 5', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('CT TNHH TM THỰC PHẨM VÕ GIA (MR THỐNG)', 'CUSTOMER', 947990988, NULL, 'Bến xe Phương Nam , Q1, HCM', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('CT TNHH DV TOTORO VN (MS HẰNG - ĐÀ NẴNG)', 'CUSTOMER', 964645079, NULL, '287 Nguyễn Chí Thanh, Phước Ninh, Hải Châu, Đà Nẵng( nhà hàng Mori Sushi).', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('CT TNHH TP NHẬT KOTO (MR KIÊN- HL)', 'CUSTOMER', 904779771, NULL, 'tổ 7, khu 8, phương Bãi Cháy, TP Hạ Long, Quảng Ninh', 5702117230);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('MR BẮC - TRƯƠNG ĐỊNH, HN', 'CUSTOMER', 986897155, NULL, 'số 10 ngõ 663 Trương Định', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('Anh Trường SSM', 'CUSTOMER', 4600205267771, NULL, NULL, NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('CT TNHH NH NAM SAN F&B (SUSHI NOWZOON)', 'CUSTOMER', NULL, NULL, 'Quận 1', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('CT TNHH MTV SHIZEN FOOD', 'CUSTOMER', '0792328259- anh Kiên (0984383533-anh nhã)', NULL, '602/45b Điện Biên Phủ, Phường 22, Quận Bình Thạnh, HCM', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('CT TNHH VIETART F&B', 'CUSTOMER', '0764477429- Anh Bình', NULL, '268 Võ Nguyên Giáp, P. Mỹ An, Q. Ngũ Hành Sơn , Tp Đà Nẵng, Việt Nam', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('CT TNHH GINKAKU ( MS THIÊN TRANG)', 'CUSTOMER', 982771994, NULL, '33 Phạm Ngũ Lão', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('CT TNHH DG GROUP (HARU - Q12)', 'CUSTOMER', NULL, NULL, '2082/3 AN PHÚ ĐÔNG 10', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('CT TNHH PGF ASIA- SG', 'CUSTOMER', 967219282, NULL, '41/24 đường số 9', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('CT TNHH PGF ASIA- HN', 'CUSTOMER', 942268638, NULL, 'số 20 ngõ 374 âu cơ', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('CT TNHH MEAT AND FISH', 'CUSTOMER', '00937 648 059', NULL, 'SỐ 1A,ĐƯỜNG SỐ 26', 317543478);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('CT TNHH NGUYÊN PHƯƠNG', 'CUSTOMER', '091 147 1749', NULL, 'khu vực chợ Bình Tân', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('CT TNHH MTV TM DV HH TP PHÚ QUỐC (ANH THỰC-PQ)', 'CUSTOMER', 973467588, NULL, NULL, NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('CT TNHH VẠN QUANG FOOD', 'CUSTOMER', '0949 248 753', NULL, 'số 21, Phạm Hồng Thái, khóm 2', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('CT TNHH OCEAN LINK VIỆT NHẬT', 'CUSTOMER', 909914082, NULL, '91 Nguyễn Phong Sắc', NULL);
INSERT INTO vgvina_partners (name, type, phone, email, address, tax_code) VALUES ('CT TNHH MTV ĐẠT PHÚ NGUYÊN', 'CUSTOMER', '090 500 67 55', NULL, NULL, NULL);

-- INSERT PRODUCTS

INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000116', 'Cá Bè Cam', 'kg', 0, 0, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000297', 'Tuna Saku 4A XK', 'kg', 0, 119.5, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000296', 'Lườn Cá Thu', 'kg', 0, 8, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000238', 'Cá Chim vây vàng đông lạnh', 'kg', 0, 2227.262, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000142', 'Mực nang nút 9-10', 'kg', 0, 11, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000192', 'Cá Ngân', 'kg', 0, 0, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000179', 'Thùng tạm', 'Cái', 0, 3, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000260', 'Loin kiếm chờ cắt steak', 'kg', 0, 0, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000102', 'Loin kiếm', 'kg', 0, 0, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000006', 'Nang roll', 'kg', 0, 0, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000007-01', 'Trứng nhum AA 100g/khay', 'kg', 0, 0, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000081', 'Râu Tako A', 'kg', 0, 25.1, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000020', 'Tuna rẻo CO', 'kg', 0, 1, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000281', 'Tôm tẩm bột xù', 'con', 0, 60, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000283', 'Tôm Thẻ', 'kg', 0, 0, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000284', 'Tôm Thẻ Lột', 'kg', 0, 0, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000285', 'Râu bạch tuộc tươi 150g up', 'kg', 0, 0, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000291', 'Tôm Sushi', 'con', 0, 0, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000292', 'Bạch Tuộc Tako 1-1.3', 'kg', 0, 0.1, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000295', 'Bạch Tuộc Tako 3up', 'kg', 0, 0.9, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000293', 'Bạch Tuộc Tako 1.3-1.5', 'kg', 0, 0, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000008', 'Râu Bạch Tuộc Tako', 'kg', 0, 14, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000269', 'Trứng Nhum Gai khay 100g', 'kg', 0, 0, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000268', 'Trứng Nhum Gai khay 200g', 'kg', 0, 0.4, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000137', 'Tako mix', 'kg', 0, 0, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000094', 'Bạch tuộc tươi size 1up', 'kg', 0, 3.4, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000058', 'Hải Sâm', NULL, 0, 0, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000247', 'Cá trích nguyên liệu', 'kg', 0, 0, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000252', 'Chả Cá Viên', 'kg', 0, 0, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000236', 'Cá tai', 'kg', 0, 0, get_or_create_product_category('Ca Tuoi'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000218', 'Chình', 'kg', 0, 0, get_or_create_product_category('Ca Tuoi'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000131', 'Mực nang lớn', 'kg', 0, 0, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000055', 'Chả Cá 250g/ bag', 'Kg', 0, 4, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000030', 'Mắt Cá Ngừ', NULL, 0, 0, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000075', 'Mùn Cưa', 'kg', 0, 5, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000155', 'Xương cá cờ kiếm', 'kg', 0, 2.3, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000044', 'Hàu Sữa tách vỏ', NULL, 0, 1, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('NHUMVUN', 'Nhum vụn', 'kg', 0, 0, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000159', 'Rẻo cá cờ kiếm', 'kg', 0, 6, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('Cá Mú', 'Cá Mú', 'kg', 0, 0, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000256', 'Kama cá ngừ', 'kg', 0, 0, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000007', 'Trứng nhum AB 200g/khay', 'kg', 0, 1, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000033', 'Lườn tuna', 'kg', 0, 2, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000294', 'Bạch Tuộc Tako 1.5-3', 'kg', 0, 0, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000086', 'Mực Nang sushi Sashimi đông khay (200g/ khay)', 'Khay', 0, 56, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES (4607060730296, 'Cá Chẽm Fillet', 'kg', 0, 10.6, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000225', 'Mực Ống Mino', 'kg', 0, 10.3, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000161', 'Lườn kiếm portion', 'kg', 0, 0, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000273', 'Mực Ống SS khay 200g', 'khay', 0, 13, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000290', 'VAT', 'lần', 0, 101, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000012', 'Lườn kiếm nướng', 'kg', 0, 20.3, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000166', 'Sushi mực ống 8g', 'khay', 0, 0, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('HAUHYOGO-M', 'Hàu Nhật Hyogo đông lạnh nguyên vỏ size M (9-11 con/kg)', 'kg', 0, 12, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000053', 'Kiếm vỉ nướng', 'kg', 0, 1, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000128', 'sụn xương cá kiếm', 'kg', 0, 18.3, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000079', 'Mực Ống', 'kg', 0, 6.6, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000232', 'Mực nang lớn (không đầu)', 'kg', 0, 0, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000011', 'Lườn kiếm sashimi', 'kg', 0, 60.2, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000076', 'Cá Trích Sashimi ( 100g/ khay)', 'khay', 0, 0, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000282', 'Bánh Takoyaki', 'kg', 0, 18, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000151', 'Loin lườn kiếm', 'kg', 0, 0, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000274', 'Cá Thu Hủ NL', 'kg', 0, 39.3, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000114', 'Cá Hố 200-300 cắt khúc', 'kg', 0, 44, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000265', 'Bạch tuộc mini 8-13', 'kg', 0, 18, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000226', 'Tuna Saku XK', 'kg', 0, 29.7, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000275', 'Cá Thu cắt lát', 'kg', 0, 70, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000005', 'Tuna Steak', 'kg', 0, 72, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000214', 'Tuna slice 200g (20pcs/khay)', 'khay', 0, 63, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000077', 'Mực Nang sushi Sashimi (160g/ khay)', 'khay', 0, 136, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000040', 'Bạch Tuộc Tako U1', 'kg', 0, 54.1, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000118', 'Chả Cá Hấp', 'kg', 0, 224.5, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000069', 'Cá Cờ Kiếm Saku', 'kg', 0, 18.1, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000002', 'Bạch tuộc tươi', 'kg', 0, 200.1, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000097', 'Tuna Saku 3A', 'kg', 0, 222.5, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000022', 'Tuna đầu đuôi portion', 'kg', 0, 4.5, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000224', 'Mực Nang 500-800', 'kg', 0, 499.2, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000004', 'Tuna Saku', 'kg', 0, 339.5, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000009-2', 'Tuna loin 3-5', 'kg', 0, 314.6, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000024', 'Tuna loin tươi', 'kg', 0, 501.5, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000010', 'Chả cá', 'kg', 0, 522, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000057', 'Kiếm Nguyên Con', 'Kg', 0, 69, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000050', 'Tuna Saku A', 'kg', 0, 430.5, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000289', 'Sò Lông Nửa Mảnh', 'kg', 0, 788.9, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000154', 'Bạch tuộc tako slice (160 gram/khay)', 'Khay', 0, 782, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000041', 'Kiếm steak', 'kg', 0, 483, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000073', 'Vẹm Xanh Tách Vỏ ( PE)', 'kg', 0, 1769, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000063', 'Vẹm Xanh Tách Vỏ', 'kg', 0, 1934, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000160', 'Phí gia công', 'kg', 0, 10, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000035', 'phí vận chuyển', 'lần', 0, 70, get_or_create_product_category('Hải Sản'));
INSERT INTO vgvina_products (sku, name, unit, price, quantity, category_id) VALUES ('SP000095', 'Nhum nguyên con (đvt: con)', 'con', 0, 19320, get_or_create_product_category('Hải Sản'));