-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. FACILITIES (Cơ sở / Kho)
CREATE TABLE IF NOT EXISTS vgvina_facilities (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name TEXT NOT NULL,
    address TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. USERS (Người dùng) - Existing table
-- Table already exists with BIGINT ID according to user feedback
-- CREATE TABLE IF NOT EXISTS vgvina_users (
--     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     username TEXT UNIQUE NOT NULL,
--     full_name TEXT NOT NULL,
--     email TEXT,
--     phone_number TEXT,
--     role TEXT,
--     status TEXT,
--     facility_id UUID REFERENCES vgvina_facilities(id),
--     created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
-- );

-- 3. PARTNERS (Khách hàng / Nhà cung cấp)
CREATE TABLE IF NOT EXISTS vgvina_partners (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name TEXT NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('CUSTOMER', 'SUPPLIER')),
    phone TEXT,
    email TEXT,
    address TEXT,
    tax_code TEXT,
    assigned_user_id BIGINT REFERENCES vgvina_users(id), -- Changed to BIGINT
    facility_id UUID REFERENCES vgvina_facilities(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. CATEGORIES (Danh mục Sản phẩm & Thu chi)
CREATE TABLE IF NOT EXISTS vgvina_product_categories (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name TEXT NOT NULL,
    description TEXT
);

CREATE TABLE IF NOT EXISTS vgvina_transaction_categories (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name TEXT NOT NULL, 
    type TEXT CHECK (type IN ('INCOME', 'EXPENSE')),
    description TEXT
);

-- 5. PRODUCTS (Sản phẩm & Kho)
CREATE TABLE IF NOT EXISTS vgvina_products (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    sku TEXT NOT NULL,
    name TEXT NOT NULL,
    unit TEXT, 
    price NUMERIC(15, 2) DEFAULT 0,
    quantity NUMERIC(15, 2) DEFAULT 0,
    category_id UUID REFERENCES vgvina_product_categories(id),
    facility_id UUID REFERENCES vgvina_facilities(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. SALES ORDERS (Đơn bán hàng)
CREATE TABLE IF NOT EXISTS vgvina_sales_orders (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    code TEXT UNIQUE NOT NULL,
    customer_id UUID REFERENCES vgvina_partners(id),
    facility_id UUID REFERENCES vgvina_facilities(id),
    assigned_user_id BIGINT REFERENCES vgvina_users(id), -- Changed to BIGINT
    order_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    status TEXT CHECK (status IN ('PENDING', 'COMPLETED', 'CANCELLED', 'DELIVERED')),
    total_amount NUMERIC(15, 2) DEFAULT 0,
    amount_paid NUMERIC(15, 2) DEFAULT 0,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS vgvina_sales_order_items (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    order_id UUID REFERENCES vgvina_sales_orders(id) ON DELETE CASCADE,
    product_id UUID REFERENCES vgvina_products(id),
    quantity NUMERIC(15, 2) NOT NULL,
    price NUMERIC(15, 2) NOT NULL,
    notes TEXT
);

-- 7. PURCHASE ORDERS (Đơn mua hàng)
CREATE TABLE IF NOT EXISTS vgvina_purchase_orders (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    code TEXT UNIQUE NOT NULL, 
    supplier_id UUID REFERENCES vgvina_partners(id),
    facility_id UUID REFERENCES vgvina_facilities(id),
    assigned_user_id BIGINT REFERENCES vgvina_users(id), -- Changed to BIGINT
    order_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    status TEXT CHECK (status IN ('PENDING', 'COMPLETED', 'CANCELLED', 'DELIVERED')),
    total_amount NUMERIC(15, 2) DEFAULT 0,
    amount_paid NUMERIC(15, 2) DEFAULT 0,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS vgvina_purchase_order_items (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    order_id UUID REFERENCES vgvina_purchase_orders(id) ON DELETE CASCADE,
    product_id UUID REFERENCES vgvina_products(id),
    quantity NUMERIC(15, 2) NOT NULL,
    price NUMERIC(15, 2) NOT NULL,
    notes TEXT
);

-- 8. FINANCIAL TRANSACTIONS (Thu / Chi)
CREATE TABLE IF NOT EXISTS vgvina_financial_transactions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    code TEXT UNIQUE NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('INCOME', 'EXPENSE', 'INTERNAL_TRANSFER')),
    transaction_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    amount NUMERIC(15, 2) NOT NULL,
    category_id UUID REFERENCES vgvina_transaction_categories(id),
    description TEXT,
    partner_id UUID REFERENCES vgvina_partners(id), 
    facility_id UUID REFERENCES vgvina_facilities(id),
    account_id UUID, 
    employee_id BIGINT REFERENCES vgvina_users(id), -- Changed to BIGINT
    related_order_id UUID, 
    related_order_type TEXT, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 9. DEBT TRANSACTIONS (Công nợ)
CREATE TABLE IF NOT EXISTS vgvina_debt_transactions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    partner_id UUID REFERENCES vgvina_partners(id),
    amount NUMERIC(15, 2) NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('RECEIVABLE', 'PAYABLE')),
    due_date DATE,
    status TEXT CHECK (status IN ('UNPAID', 'PARTIALLY_PAID', 'PAID')),
    facility_id UUID REFERENCES vgvina_facilities(id),
    assigned_user_id BIGINT REFERENCES vgvina_users(id), -- Changed to BIGINT
    notes TEXT,
    related_order_id UUID,
    related_order_type TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 10. ACCOUNTS (Tài khoản thanh toán)
CREATE TABLE IF NOT EXISTS vgvina_accounts (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name TEXT NOT NULL,
    type TEXT, -- 'CASH', 'BANK'
    balance NUMERIC(15, 2) DEFAULT 0,
    facility_id UUID REFERENCES vgvina_facilities(id), -- Có thể null nếu là tk công ty
    details TEXT
);

-- BASIC RLS POLICIES (Row Level Security)
-- Bật RLS cho tất cả các bảng
ALTER TABLE vgvina_facilities ENABLE ROW LEVEL SECURITY;
ALTER TABLE vgvina_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE vgvina_partners ENABLE ROW LEVEL SECURITY;
ALTER TABLE vgvina_products ENABLE ROW LEVEL SECURITY;
ALTER TABLE vgvina_sales_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE vgvina_purchase_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE vgvina_financial_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE vgvina_debt_transactions ENABLE ROW LEVEL SECURITY;

-- Policy đơn giản: Cho phép truy cập public (anon) cho demo hiện tại.
-- TODO: Cập nhật thành Authenticated users only khi có Auth.
CREATE POLICY "Public Access" ON vgvina_facilities FOR ALL USING (true);
CREATE POLICY "Public Access" ON vgvina_users FOR ALL USING (true);
CREATE POLICY "Public Access" ON vgvina_partners FOR ALL USING (true);
CREATE POLICY "Public Access" ON vgvina_products FOR ALL USING (true);
CREATE POLICY "Public Access" ON vgvina_sales_orders FOR ALL USING (true);
CREATE POLICY "Public Access" ON vgvina_sales_order_items FOR ALL USING (true);
CREATE POLICY "Public Access" ON vgvina_purchase_orders FOR ALL USING (true);
CREATE POLICY "Public Access" ON vgvina_purchase_order_items FOR ALL USING (true);
CREATE POLICY "Public Access" ON vgvina_financial_transactions FOR ALL USING (true);
CREATE POLICY "Public Access" ON vgvina_debt_transactions FOR ALL USING (true);
CREATE POLICY "Public Access" ON vgvina_product_categories FOR ALL USING (true);
CREATE POLICY "Public Access" ON vgvina_transaction_categories FOR ALL USING (true);

-- INITIAL SEED DATA (Dữ liệu mẫu cơ bản)
-- Create 1 Facility
INSERT INTO vgvina_facilities (name, address) VALUES ('Chi nhánh trung tâm', 'Hà Nội');


create table public.vgvina_users (
  id bigint generated by default as identity not null,
  username text not null,
  password_hash text not null,
  full_name text null,
  email text null,
  phone_number text null,
  role text null default 'Guest'::text,
  status text null default 'Pending'::text,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  last_login_at timestamp with time zone null,
  role_id uuid null,
  constraint vgvina_users_pkey primary key (id),
  constraint vgvina_users_username_key unique (username),
  constraint vgvina_users_role_id_fkey foreign KEY (role_id) references vgvina_roles (id) on delete set null
) TABLESPACE pg_default;

create index IF not exists idx_users_username on public.vgvina_users using btree (username) TABLESPACE pg_default;

create index IF not exists idx_users_role on public.vgvina_users using btree (role_id) TABLESPACE pg_default;

create trigger audit_users_changes
after INSERT
or DELETE
or
update on vgvina_users for EACH row
execute FUNCTION audit_log_changes ();